[package]
name = "prisma-cli"
version = "0.0.0"
edition = "2021"

[dependencies]
prisma-client-rust-cli = { features = [
  "sqlite-create-many",
  # "rspc",
], path = "../cli" }

[[bin]]
name = "prisma-cli"
path = "src/bin/prisma.rs"
